<a href="https://colab.research.google.com/github/Surabhi-Sunil/HomeSchoolTrendsInUSA/blob/main/Home_school.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

district = pd.read_csv('/content/home_school_district.csv')
data_dictionary = pd.read_csv('/content/home_school_data_dictionary.csv')
state = pd.read_csv('/content/home_school_state.csv')

In [ ]:
data_dictionary

   HOME_SCHOOL_DISTRICT.csv                                         Unnamed: 1
0                     Field                                         Definition
1                  lea_name  Official name of the local education agency (s...
2                    lea_id  official id for the local education agency (sc...
3                     state                     Postal code state abbreviation
4                      year  Reflects the academic school year. Homeschooli...
5       homeschool_students  The number of home-schooling students reported...
6                       NaN                                                NaN
7                       NaN                                                NaN
8                       NaN                                                NaN
9     HOME_SCHOOL_STATE.csv                                                NaN
10                    Field                                         Definition
11                    state                                    Full state name
12                     year  Reflects the academic school year. Homeschooli...
13      homeschool_students  The number of home-schooling students reported...

In [ ]:
state.head(10)

           state     year  homeschool_students
0     CALIFORNIA  2017-18              26345.0
1       COLORADO  2017-18               7387.0
2       DELAWARE  2017-18               2864.0
3        FLORIDA  2017-18              89817.0
4         KANSAS  2017-18               1947.0
5       KENTUCKY  2017-18              24573.0
6      LOUISIANA  2017-18              21717.0
7       MARYLAND  2017-18              26040.0
8  MASSACHUSETTS  2017-18               7435.0
9      MINNESOTA  2017-18              18988.0

In [ ]:
state.isna().sum()

state                  0
year                   0
homeschool_students    6
dtype: int64

In [ ]:
null_rows = state[state['homeschool_students'].isnull()]
print(null_rows['state'])

22            MAINE
55            MAINE
88            MAINE
177    RHODE ISLAND
194    PENNSYLVANIA
195       TENNESSEE
Name: state, dtype: object

In [ ]:
state['state'].duplicated().value_counts()

state
True     165
False     33
Name: count, dtype: int64

In [ ]:
state['state'].unique()

array(['CALIFORNIA', 'COLORADO', 'DELAWARE', 'FLORIDA', 'KANSAS',
       'KENTUCKY', 'LOUISIANA', 'MARYLAND', 'MASSACHUSETTS', 'MINNESOTA',
       'NEW YORK', 'NORTH DAKOTA', 'RHODE ISLAND', 'SOUTH CAROLINA',
       'SOUTH DAKOTA', 'VIRGINIA', 'WASHINGTON', 'WYOMING', 'ARKANSAS',
       'DISTRICT OF COLUMBIA', 'GEORGIA', 'HAWAII', 'MAINE',
       'MISSISSIPPI', 'MONTANA', 'NEBRASKA', 'NEW HAMPSHIRE',
       'NEW MEXICO', 'OHIO', 'PENNSYLVANIA', 'TENNESSEE', 'VERMONT',
       'WISCONSIN'], dtype=object)

In [ ]:
state['year'].unique()

array(['2017-18', '2018-19', '2019-20', '2020-21', '2021-22', '2022-23'],
      dtype=object)

In [ ]:
state.groupby(['state', 'year'])['homeschool_students'].sum()

state     year
ARKANSAS  2017-18    20331.0
          2018-19    21959.0
          2019-20    22249.0
          2020-21    30267.0
          2021-22    30205.0
                      ...
WYOMING   2018-19     1797.0
          2019-20     2585.0
          2020-21     3884.0
          2021-22     3475.0
          2022-23     3769.0
Name: homeschool_students, Length: 198, dtype: float64

In [ ]:
district.head()

               lea_name   lea_id state     year  homeschool_students
0  Alma School District  0502250    AR  2017-18                142.0
1  Alma School District  0502250    AR  2018-19                191.0
2  Alma School District  0502250    AR  2019-20                204.0
3  Alma School District  0502250    AR  2020-21                269.0
4  Alma School District  0502250    AR  2021-22                311.0

In [ ]:
district['state'].unique()

array(['AR', 'FL', 'MD', 'WA', 'LA', 'TN', 'KY', 'KS', 'MA', 'GA', 'PA',
       'VA', 'WI', 'MN', 'OH', 'NH', 'NM', 'WY', 'SD', 'SC', 'RI', 'ND',
       'NY', 'MS', 'ME', 'HI', 'DE', 'DC', 'CO', 'CA'], dtype=object)

In [ ]:
district.isna().sum()

lea_name                37
lea_id                  35
state                    0
year                     0
homeschool_students    482
dtype: int64

In [ ]:
null_rows = district[district['homeschool_students'].isnull()]
print(null_rows)

                          lea_name   lea_id state     year  \
41         Augusta School District  0502670    AR  2022-23
335        Dermott School District  0505170    AR  2022-23
382          Earle School District  0505550    AR  2022-23
646        Horatio School District  0507860    AR  2022-23
1245   Spring Hill School District  0512630    AR  2022-23
...                            ...      ...   ...      ...
30602                          NaN      NaN    MS  2019-20
30603                          NaN      NaN    MS  2020-21
30604                          NaN      NaN    MS  2021-22
30605                          NaN      NaN    MS  2022-23
31087      Talmadge Public Schools  2312810    ME  2020-21

       homeschool_students
41                     NaN
335                    NaN
382                    NaN
646                    NaN
1245                   NaN
...                    ...
30602                  NaN
30603                  NaN
30604                  NaN
30605                  NaN
31087                  NaN

[482 rows x 5 columns]

In [ ]:
district.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37674 entries, 0 to 37673
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   lea_name             37637 non-null  object
 1   lea_id               37639 non-null  object
 2   state                37674 non-null  object
 3   year                 37674 non-null  object
 4   homeschool_students  37192 non-null  float64
dtypes: float64(1), object(4)
memory usage: 1.4+ MB

In [ ]:
district_cleaned = district.dropna()
district_cleaned.isna().sum()

lea_name               0
lea_id                 0
state                  0
year                   0
homeschool_students    0
dtype: int64

In [ ]:
district_cleaned.shape

(37167, 5)

In [ ]:
state.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198 entries, 0 to 197
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   state                198 non-null    object
 1   year                 198 non-null    object
 2   homeschool_students  192 non-null    float64
dtypes: float64(1), object(2)
memory usage: 4.8+ KB